apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-worker
  namespace: historia-clinica-distribuida
spec:
  serviceName: citus-worker
  replicas: 2
  selector:
    matchLabels:
      app: citus-worker
  template:
    metadata:
      labels:
        app: citus-worker
    spec:
      containers:
      - name: citus
        image: citusdata/citus:11.2
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: citus-worker
  namespace: historia-clinica-distribuida
spec:
  clusterIP: None
  selector:
    app: citus-worker
  ports:
  - port: 5432
    targetPort: 5432
